// generated by stringer -type=Symbol; DO NOT EDIT

package main

import "fmt"

const _Symbol_name = "AAAA0AA1AA2AEAE0AE1AE2AHAH0AH1AH2AOAO0AO1AO2AWAW0AW1AW2AYAY0AY1AY2BCHDDHEHEH0EH1EH2ERER0ER1ER2EYEY0EY1EY2FGHHIHIH0IH1IH2IYIY0IY1IY2JHKLMNNGOWOW0OW1OW2OYOY0OY1OY2PRSSHTTHUHUH0UH1UH2UWUW0UW1UW2VWYZZHInvalid"

var _Symbol_index = [...]uint8{0, 2, 5, 8, 11, 13, 16, 19, 22, 24, 27, 30, 33, 35, 38, 41, 44, 46, 49, 52, 55, 57, 60, 63, 66, 67, 69, 70, 72, 74, 77, 80, 83, 85, 88, 91, 94, 96, 99, 102, 105, 106, 107, 109, 111, 114, 117, 120, 122, 125, 128, 131, 133, 134, 135, 136, 137, 139, 141, 144, 147, 150, 152, 155, 158, 161, 162, 163, 164, 166, 167, 169, 171, 174, 177, 180, 182, 185, 188, 191, 192, 193, 194, 195, 197, 204}

func (i Symbol) String() string {
	if i+1 >= Symbol(len(_Symbol_index)) {
		return fmt.Sprintf("Symbol(%d)", i)
	}
	return _Symbol_name[_Symbol_index[i]:_Symbol_index[i+1]]
}
